config/routes.rb
CmmKb::Application.routes.draw do

  resources :daves


  get 'tags/:tag', to: 'tags#show', as: :tag


  resources :articles do
    collection do
      get :search
    end
  end 

  resources :categories

  root :to => 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  require 'will_paginate/array'

  # For new articles, validate the presence of each of these fields
  validates :author, presence: true
  validates :body, presence: true
  validates :title, presence: true
  validates :category_id, presence: true

  attr_accessible :author, :body, :public, :title, :category_id, :date, :revisions, :tag_list
  acts_as_taggable
  ActsAsTaggableOn.force_lowercase = true
  belongs_to :category

  def self.search(search, page)
  	search_string = "%" + search + "%"
    conditions = nil
    unless search.blank?
      conditions = ['title LIKE ? OR body LIKE ? OR tags LIKE ?', search_string, search_string, search_string]
    end
    paginate :per_page => 5, :page => page, :conditions => conditions, :order => 'title'

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json

def index

  if params[:tag]
    p "YES TAG PARAM"
    @articles = Article.tagged_with(params[:tag])
  else
    @articles = Article.all(:order => 'created_at DESC')
  end
  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @articles }
  end
end



def search
  @articles = Article.search(params[:search], params[:page])

  respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
  end
end



  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        @article.increment!(:revisions)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	# Might not use this...looking into gem for tagging
	def show_tags(article)
		tags = article.tags.try(:split, ",") || tags = ""
		#tags = tags.split('/,/')
		if tags.length > 0
			tag_links = ""
			tags.each do |tag|
				tag_links +=  link_to tag, :controller => "articles", :action => 'search', :search => tag
			end
			return raw(tag_links)
		else
			return "No tags! Consider adding some for search performance."
		end
	end


end

app/views/articles/_form.html.erb
<% title "Article" %>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation" class="alert-box alert">
      <p><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</p>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-5 columns end">
    <%= f.label :title %>
    <%= f.text_field :title %>
    </div>
  </div>
  
  <div class="row" id="epiceditor" style="height: 400px;">
    <%= f.label :body %>
    <%= f.text_area :body, :id => 'body_txt', :cols => 40, :rows => 10 %>
  </div>

  <div class="row article-form-meta">
    <div class="large-3 columns">
      <%= f.label :category_id %>
      <%= collection_select(:article, :category_id, Category.all, :id, :title, options ={:prompt => "Select a category"}) %>
    </div>
    <div class="large-6 columns">
      <%= f.label :New_Category %>
      <div class="large-6 columns"><input type="text" name="new_cat" id="new_cat" placeholder="New category..."></div>
      <div class="large-3 columns end"><a href="javascript:void(0)" class="tiny button" onclick="addCategory()">Add new</a></div>
    </div>
    <div class="large-3 columns end">
       <%= f.label :Visibility %><br>
      <%= f.check_box :public %><%= f.label :public %>
    </div>
  </div>
  
  <div class="row">
     <div class="large-5 columns">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list, id: 'e2' %>

      </div>
      <div class="large-2 columns end">
      <%= f.label :author %>
      <%= f.text_field :author %>
      </div>
    </div>
  </div>

<script>
  var tagArray = [
  <% ActsAsTaggableOn::Tag.all.map do |t| %>
  "<%= t.name %>",
  <% end %>
  ];
</script>

  <div class="row">
    <div class="actions">
    <%= f.submit "Submit", :onclick => 'setEpicValue()', class: "small success button" %>
    <%= link_to 'Cancel', @article, class: "small alert button" %>
  </div>
  </div>

 <%= f.hidden_field :body, :id => 'article_body'%>

<% end %>

app/views/articles/_search.html.erb
<%= form_tag({controller: 'articles', action: 'search'}, method: 'get') do %>
    <div class="row collapse">
	    <div class="small-9 columns">
	      <%= text_field_tag :search, params[:search], :id => 'search_field', :placeholder => "Search..." %>
	    </div>
	    <div class="small-3 columns">
	      <%= submit_tag "Search", :name => nil, :class => "small button postfix" %> 
	    </div>
	</div>
<% end %>

app/views/articles/edit.html.erb
<div class="row">
	<h1>Editing article</h1>
	<%= render 'form' %>
	<div class="center">
		<%= link_to 'Show', @article %> |
		<%= link_to 'Home', articles_path %>
	</div>
</div>

app/views/articles/index.html.erb
<% @articles = Article.paginate(:page => params[:page], :per_page => 10) %>
<div class="row article-meta">
  <div class="top-article-count"><div class="pagination-info"><%= page_entries_info @articles %></div></div>
  <div class="top-article-pagination"><%= will_paginate @articles, :renderer => PaginationListLinkRenderer, :previous_label => '&laquo;', :next_label => '&raquo;' %></div>
</div>
<% @articles.each do |article| %>
<div class="row panel">
  <div class="large-12 columns">
    <div class="row"><h1><%= link_to article.title, article %></h1></div>
    <div class="row">
      <div class="article-meta">
      <%= image_tag("icons/icon-category.png", class: "global-icon") %> Category: <%= link_to article.category.title, category_path(article.category), class: "round label success" %> | 
      <%= image_tag("icons/icon-tag.png", class: "global-icon") %> Tags: <%= article.tag_list.count > 0 ? (raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) : raw("<em>None</em>") %> |
      <%= image_tag("icons/icon-user.png", class: "global-icon") %> Created by: <em><%= article.author %></em> | 
      <%= image_tag("icons/icon-update.png", class: "global-icon") %> Last updated: <%= prettyTime(article.updated_at) == prettyTime(Date.today) ? "Today" : prettyTime(article.updated_at) %><br>
      
      </div>
    </div>
    <div class="row">
      <div class="article-body"><%= truncate(article.body, length: 200) %></div>
    </div>
  </div>
</div>

<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= will_paginate @articles, :renderer => PaginationListLinkRenderer, :previous_label => '&laquo;', :next_label => '&raquo;' %>
    <div class="pagination-info"><%= page_entries_info @articles %></div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
	<h1>New article</h1>
	<%= render 'form' %>
</div>

app/views/articles/search.html.erb

<div class="search-result-wrapper">
<div class="row">
<h4>Found <%= pluralize(@articles.count, 'result') %></h4>

<% results = @articles.paginate(:page => params[:page], :per_page => 10) %>
<div class="pagination-info"><%= page_entries_info results %></div>
<ul>
	<% results.each do |article| %>
		<li class="search-result">
			<div class="large-12 columns">
				<b><%= link_to article.title, article %></b>
				<p><%= truncate(article.body, length: 200) %> <br>
				<em class="search-result-date">Updated: <%= prettyTime(article.updated_at) %></em> 
				<%= link_to article.category.title, article.category, class: 'round success label' %>
				<span class="search-result-author"><%= article.author%></span></p>
			</div>
		</li>
	<% end %>
</ul>
<br style="clear:both;">

<%= will_paginate results, :renderer => PaginationListLinkRenderer, :previous_label => '&laquo;', :next_label => '&raquo;' %>
<div class="pagination-info"><%= page_entries_info results %></div>
</div>
</div>

app/views/articles/show.html.erb
<% title @article.title %>

<div class="row panel">
	<% if flash[:notice] %>
   		<div class="alert-box"><%= flash[:notice] %></div>
  	<% end %>
	
	<h1><%= @article.title.titleize %></h1>
	<span class="subheader">Created on <%= prettyTime(@article.created_at) %> by <em><%= @article.author %></em></span>

	<hr />

	<div class="row">
		<div class="large-9 columns">
			<%= markdown @article.body %>
		</div>
		<div class="large-3 columns article-sidebar">
			<%= image_tag("icons/icon-category.png", class: "sidebar-icon") %> <b>Category:</b> <%= link_to Category.find(@article.category).title, category_path(@article.category), class: 'label round success' %> <br>
			<%= image_tag("icons/icon-clock.png", class: "sidebar-icon") %> <b>Created:</b> <%= prettyTime(@article.created_at) == prettyTime(Date.today) ? "Today" : prettyTime(@article.created_at) %> <br>
			<%= image_tag("icons/icon-user.png", class: "sidebar-icon") %> <b>Author:</b> <%= @article.author %> <br>
			<%= image_tag("icons/icon-tag.png", class: "sidebar-icon") %> <b>Tags:</b> <%= @article.tag_list.count > 0 ? (raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) : raw("<em>None</em>") %><br>
			<%= image_tag("icons/icon-update.png", class: "sidebar-icon") %> 
				<b>Revised:</b> 
				<%= @article.revisions == nil ? "Never" : (prettyTime(@article.updated_at) == prettyTime(Date.today) ? "Today" : prettyTime(@article.updated_at)) %> 
				<br>
			<%= image_tag("icons/icon-graph.png", class: "sidebar-icon") %>  <b>Revisions:</b> <%= @article.revisions == nil ? 0 : @article.revisions %> <br>
			<%= image_tag("icons/icon-public.png", class: "sidebar-icon") %> <b>Public:</b> <%= @article.public %>
		</div>

	</div>

	<div class="article-controls center">
		<!-- <%= link_to 'Back', articles_path, class: "tiny button" %> -->
		<%= link_to 'Edit', edit_article_path(@article), class: 'tiny button' %> 
		<%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tiny alert button' %>
	</div>
</div>