config/routes.rb
CmmKb::Application.routes.draw do

  resources :daves


  get 'tags/:tag', to: 'tags#show', as: :tag


  resources :articles do
    collection do
      get :search
    end
  end 

  resources :categories

  root :to => 'articles#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  # Vaidation
  validates :title, presence: true

  attr_accessible :public, :title
  has_many :articles
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
     
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert-box alert">
      <p><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</p>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-3 small-centered columns">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="actions center">
    <%= f.submit "Submit", class: 'small button' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="row">
<%= link_to 'New Category', new_category_path, class: 'tiny button' %>
	<div class="large-8 columns small-centered">
	
	<table>
		<thead>
			<tr>
				<th>Category</th>
				<th>Article count</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @categories.each do |category| %>
				<tr>
					<td><%= link_to category.title, category %></td>
					<td><%= category.articles.count %></td>
					<td>
						<%= link_to edit_category_path(category) do %><span class="tiny secondary button"><%= image_tag("icons/icon-edit.png", class: 'global-icon') %> Edit</span><% end %> 

						<% if category.articles.count == 0 %>
						<%= link_to category, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="tiny alert button"><%= image_tag("icons/icon-delete.png", class: 'global-icon') %> Delete</span><% end %>
						<% else %>
						<span data-tooltip class="has-tip" title="Can't delete category; would orphan articles. Reassign articles to different category first.">
							<span class="tiny alert button disabled"><%= image_tag("icons/icon-delete.png", class: 'global-icon') %> Delete</span>
						</span>
						<% end %> </td>
				</tr>
			<% end %>
		</tbody>
	</table>

	</div>

</div>


app/views/categories/new.html.erb
<div class="row">
	<h1>New category</h1>

	<%= render 'form' %>
	<div class="center">
		<%= link_to 'Back', categories_path %>
	</div>
</div>

app/views/categories/show.html.erb
<% title @category.title %>
<div class="row">
	<h1><%= @category.title %> <span class="round label article-header-count-badge"><%= @category.articles.count %> Articles</span></h1>
	<p>Showing articles under category <em class="serif"><%= @category.title %></em>.</p>
</div>
<% cat_articles = @category.articles.paginate(:page => params[:page], :per_page => 5) %>
<% cat_articles.each do |article| %>
	<div class="row panel">
	  <div class="large-12 columns">
	    <div class="row"><h1><%= link_to article.title, article %></h1></div>
	    <div class="row">
	      <div class="article-meta">
	      <%= image_tag("icons/icon-category.png", class: "global-icon") %> Category: <%= link_to article.category.title, category_path(article.category), class: "round label success" %> | 
	      <%= image_tag("icons/icon-tag.png", class: "global-icon") %> Tags: <%= article.tag_list.count > 0 ? (raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) : raw("<em>None</em>") %> |
	      <%= image_tag("icons/icon-user.png", class: "global-icon") %> Created by: <em><%= article.author %></em> | <%= image_tag("icons/icon-update.png", class: "global-icon") %> Last updated: <%= article.updated_at = Date.today ? "Today" : article.updated_at %><br>
	      <!-- Tags: <%= article.tags  %> -->
	      </div>
	    </div>
	    <div class="row">
	      <div class="article-body"><%= truncate(article.body, length: 200) %></div>
	    </div>
	  </div>
	</div>

<% end %>

<div class="row">
  <div class="large-12 columns">
    <%= will_paginate cat_articles, :renderer => PaginationListLinkRenderer %>
    <%= page_entries_info cat_articles %>
  </div>
</div>