config/routes.rb
CmmKb::Application.routes.draw do

  resources :daves


  get 'tags/:tag', to: 'tags#show', as: :tag


  resources :articles do
    collection do
      get :search
    end
  end 

  resources :categories

  root :to => 'articles#index'
end

app/views/layouts/_footer.html.erb
<div class="row">
	&copy; <%= Time.now.year %> Some copyright text. All rights are probably reserved.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>MySite - <%= content_for?(:title) ? yield(:title) + " - Knowledgebase" : "Knowledgebase" %></title>
<%= stylesheet_link_tag    "application" %>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<%= javascript_include_tag "vendor/modernizr" %>
<%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="row">
    <div class="large-3 columns">
      <div class="logo-wrapper">
      <%= link_to(image_tag("logo.png"), root_url ) %>  <br>
      <%= link_to(image_tag("article-default.png", class: 'logo-book'), root_url ) %>
      <%= link_to("Knowledgebase", root_url) %>
      </div>
    </div>
    <div class="large-9 columns">
        <div class="header-controls">
          <ul class="button-group">
           <li><a href="#" class="tiny button success">Login</a></li>
           <li><a href="#" data-dropdown="hover1" data-options="is_hover:true" class="tiny button">New</a>
          <ul id="hover1" class="content f-dropdown" data-dropdown-content>
            <li><%= link_to "New Article", new_article_path %></li>
            <li><%= link_to "New Category", new_category_path %></li>
          </ul>
          </li>
          </ul>
        </div>
    </div>
    </div>
    <!-- BEGIN Search -->
    <div class="row">
      <div class="small-8 large-5 centered">
       <%= render partial: 'articles/search' %>
      </div>
    </div>
    <!-- END Search -->
  
</header>

<div class="main-content">
  <%= yield %>
</div>

<div class="global-footer">
  <%= render partial: 'layouts/footer' %>
</div>
<%= javascript_include_tag "application" %>
</body>
</html>